server:
  port: 8080
  error:
    include-binding-errors: always 
    include-message: always
    include-stacktrace: always
# Oracle #
spring:
  datasource:
    url: jdbc:oracle:thin:@localhost:1521:orcl
    username: david
    password: 123456
    driverClassName: oracle.jdbc.OracleDriver
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
  mvc:
    log-request-details: true